services:
  db:
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_USER: 'coins'
      POSTGRES_PASSWORD: 'coinsSecret5'
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  db-test:
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'coins'
      POSTGRES_PASSWORD: 'coinsSecret5'
    ports:
      - '5442:5432'
    volumes:
      - db-data-test:/var/lib/postgresql/data
volumes:
  db-data:
  db-data-test:
