INSERT INTO countries(name, url)
VALUES ('AUSTRIA', 'https://flagpedia.net/data/flags/w1160/at.webp'),
       ('ANDORRA', 'https://flagpedia.net/data/flags/w1160/ad.webp'),
       ('BELGIUM', 'https://flagpedia.net/data/flags/w1160/be.webp'),
       ('CROATIA', 'https://flagpedia.net/data/flags/w1160/hr.webp'),
       ('CYPRUS', 'https://flagpedia.net/data/flags/w1160/cy.webp'),
       ('ESTONIA', 'https://flagpedia.net/data/flags/w1160/ee.webp'),
       ('FINLAND', 'https://flagpedia.net/data/flags/w1160/fi.webp'),
       ('FRANCE', 'https://flagpedia.net/data/flags/w1160/fr.webp'),
       ('GERMANY', 'https://flagpedia.net/data/flags/w1160/de.webp'),
       ('GREECE', 'https://flagpedia.net/data/flags/w1160/gr.webp'),
       ('IRELAND', 'https://flagpedia.net/data/flags/w1160/ie.webp'),
       ('ITALY', 'https://flagpedia.net/data/flags/w1160/it.webp'),
       ('KOSOVO', 'https://flagpedia.net/data/flags/w1160/xk.webp'),
       ('LATVIA', 'https://flagpedia.net/data/flags/w1160/lv.webp'),
       ('LITHUANIA', 'https://flagpedia.net/data/flags/w1160/lt.webp'),
       ('LUXEMBOURG', 'https://flagpedia.net/data/flags/w1160/lu.webp'),
       ('MALTA', 'https://flagpedia.net/data/flags/w1160/mt.webp'),
       ('MONACO', 'https://flagpedia.net/data/flags/w1160/mc.webp'),
       ('MONTENEGRO', 'https://flagpedia.net/data/flags/w1160/me.webp'),
       ('NETHERLANDS', 'https://flagpedia.net/data/flags/w1160/nl.webp'),
       ('PORTUGAL', 'https://flagpedia.net/data/flags/w1160/pt.webp'),
       ('SAN_MARINO', 'https://flagpedia.net/data/flags/w1160/sm.webp'),
       ('SLOVAKIA', 'https://flagpedia.net/data/flags/w1160/sk.webp'),
       ('SLOVENIA', 'https://flagpedia.net/data/flags/w1160/si.webp'),
       ('SPAIN', 'https://flagpedia.net/data/flags/w1160/es.webp'),
       ('VATICAN_CITY', 'https://flagpedia.net/data/flags/w1160/va.webp');


INSERT INTO coins(name, country_id, year, url)
VALUES ('75th anniversary', (SELECT id FROM countries WHERE name = 'VATICAN_CITY'), 2004,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_va.webp'),
       ('World food program', (SELECT id FROM countries WHERE name = 'ITALY'), 2004,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_it.webp'),
       ('Bartolomeo Borghesi', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2004,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_sm.webp'),
       ('EU enlargement', (SELECT id FROM countries WHERE name = 'FINLAND'), 2004,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_fi.webp'),
       ('Henri', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2004,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_lu.webp'),
       ('Olympic Games Athens', (SELECT id FROM countries WHERE name = 'GREECE'), 2004,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_el.webp'),
       ('20th World Youth Day', (SELECT id FROM countries WHERE name = 'VATICAN_CITY'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_va.webp'),
       ('World Year of Physics 2005', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_sm.webp'),
       ('1st anniversary of the signing of the European Constitution', (SELECT id FROM countries WHERE name = 'ITALY'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_it.webp'),
       ('Finlands 50th anniversary of membership of UN', (SELECT id FROM countries WHERE name = 'FINLAND'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_fi.webp'),
       ('50th anniversary of Austrian State Treaty', (SELECT id FROM countries WHERE name = 'AUSTRIA'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_at.webp'),
       ('400th anniversary of first edition of Don Quixote', (SELECT id FROM countries WHERE name = 'SPAIN'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_sp.webp'),
       ('Belgium-Luxembourg Economic Union', (SELECT id FROM countries WHERE name = 'BELGIUM'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_be.webp'),
       ('50th anniversary of Grand Duke Henri and 100th anniversary of death of Grand Duke Adolphe', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2005,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_lu_2.webp'),
       ('500th anniversary of Swiss Pontifical Guard', (SELECT id FROM countries WHERE name = 'VATICAN_CITY'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_va.webp'),
       ('500th anniversary of Christopher Columbus death', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_sm.webp'),
       ('100th anniversary of universal and equal suffrage', (SELECT id FROM countries WHERE name = 'FINLAND'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_fi.webp'),
       ('Atomium', (SELECT id FROM countries WHERE name = 'BELGIUM'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_be.webp'),
       ('Schelswig-Holstein', (SELECT id FROM countries WHERE name = 'GERMANY'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_de.webp'),
       ('Olympic Winter Games', (SELECT id FROM countries WHERE name = 'ITALY'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_it.webp'),
       ('25th anniversary of Grand-Duke Guillaume', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2006,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_lu.webp'),
       ('90th anniversary of Finlands independence', (SELECT id FROM countries WHERE name = 'FINLAND'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Finland.webp'),
       ('200th anniversary of birth of Giuseppe Garibaldi', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_San_marino.webp'),
       ('80th anniversary of Pope Benedict XVI', (SELECT id FROM countries WHERE name = 'VATICAN_CITY'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_va.webp'),
       ('25th anniversary of death of Princess Grace', (SELECT id FROM countries WHERE name = 'MONACO'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Monaco.webp'),
       ('Portuguese Presidency of the European Union', (SELECT id FROM countries WHERE name = 'PORTUGAL'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Portugal.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'AUSTRIA'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Austria.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'BELGIUM'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Belgium.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'FINLAND'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Finland.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'FRANCE'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_France.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'GERMANY'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Germany.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'GREECE'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Greece.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'IRELAND'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Ireland.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'ITALY'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Italy.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Luxembourg.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'NETHERLANDS'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Netherlands.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'PORTUGAL'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Portugal.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'SLOVENIA'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Slovenia.webp'),
       ('50th anniversary of the Treaty of Rome', (SELECT id FROM countries WHERE name = 'SPAIN'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Spain.webp'),
       ('Mecklenburg-Vorpommern', (SELECT id FROM countries WHERE name = 'GERMANY'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Germany.webp'),
       ('Grand Ducal Palace', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2007,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_luxembourg.webp'),
       ('Year of St. Paul', (SELECT id FROM countries WHERE name = 'VATICAN_CITY'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Vatican.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', (SELECT id FROM countries WHERE name = 'FINLAND'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Finland.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', (SELECT id FROM countries WHERE name = 'PORTUGAL'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Finland.webp'),
       ('French Presidency of Council of the European Union', (SELECT id FROM countries WHERE name = 'FRANCE'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_France1.webp'),
       ('500th anniversary of Primož Trubars birth', (SELECT id FROM countries WHERE name = 'SLOVENIA'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Slovenia.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', (SELECT id FROM countries WHERE name = 'BELGIUM'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Belgium.webp'),
       ('European Year of Intercultural Dialogue', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_San_Marino.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', (SELECT id FROM countries WHERE name = 'ITALY'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Italy.webp'),
       ('Grand-Duke Henri and Château de Berg', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_luxembourg.webp'),
       ('Hamburg', (SELECT id FROM countries WHERE name = 'GERMANY'), 2008,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_de.webp'),

       ('Change head of state', (SELECT id FROM countries WHERE name = 'SPAIN'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Spain_Head.webp'),
       ('Fight against AIDS', (SELECT id FROM countries WHERE name = 'FRANCE'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_France_2.webp'),
       ('100th anniversary of birth of Ilmari Tapiovaara', (SELECT id FROM countries WHERE name = 'FINLAND'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Finland_2.webp'),
       ('25th anniversary of the fall of the Berlin Wall', (SELECT id FROM countries WHERE name = 'VATICAN_CITY'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Vatican.webp'),
       ('600th anniversary of crowning of Barbara Celjska', (SELECT id FROM countries WHERE name = 'SLOVENIA'), 2009,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Slovenia.webp'),
       ('50th anniversary of accension to the throne of Grand-Duke Jean', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Luxembourg_2.webp'),
       ('International Year of Family Farming', (SELECT id FROM countries WHERE name = 'PORTUGAL'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Portugal_Farming.webp'),
       ('Malta Independence 1964', (SELECT id FROM countries WHERE name = 'MALTA'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Malta_2.webp'),
       ('90th anniversary of death of Giacomo Puccini', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_San_Marino_Puccini.webp'),
       ('150 years of Belgian Red Cross', (SELECT id FROM countries WHERE name = 'BELGIUM'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Belgium_Cross.webp'),
       ('150th anniversary of union of the Ionian Islands with Greece', (SELECT id FROM countries WHERE name = 'GREECE'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Greece.webp'),
       ('400 years since the death of Demenikos Theotokopoulos', (SELECT id FROM countries WHERE name = 'GREECE'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Greece_2.webp'),
       ('Riga - European Capital of Culture 2014', (SELECT id FROM countries WHERE name = 'LATVIA'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Latvia.webp'),
       ('200 years of Malta Police Force', (SELECT id FROM countries WHERE name = 'MALTA'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Malta.webp'),
       ('500th anniversary of the death of Bramante Lazzari delle Penne di San Marino', (SELECT id FROM countries WHERE name = 'SAN_MARINO'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_San_Marino_Lazzari.webp'),
       ('100th anniversary of the birth of Tove Jansson', (SELECT id FROM countries WHERE name = 'FINLAND'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Finland.webp'),
       ('200th anniversary of the foundation of Arma dei Carabinieri', (SELECT id FROM countries WHERE name = 'ITALY'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Italy.webp'),
       ('450th anniversary of the birth of Galileo Galilei', (SELECT id FROM countries WHERE name = 'ITALY'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Italy_2.webp'),
       ('70th anniversary of the Normany landings', (SELECT id FROM countries WHERE name = 'FRANCE'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_France.webp'),
       ('Official farewell of former Queen Beatrix', (SELECT id FROM countries WHERE name = 'NETHERLANDS'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Netherlands.webp'),
       ('10th anniversary of Slovak accension to the European Union', (SELECT id FROM countries WHERE name = 'SLOVAKIA'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Slovakia.webp'),
       ('40th anniversary of the 25th April Revolution', (SELECT id FROM countries WHERE name = 'PORTUGAL'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Portugal.webp'),
       ('100th anniversary of the start of the First World War', (SELECT id FROM countries WHERE name = 'BELGIUM'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Belgium.webp'),
       ('UNESCOs World Cultural and Natural Heritage Sites - Park Güell', (SELECT id FROM countries WHERE name = 'SPAIN'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Spain.webp'),
       ('20 years in the Council of Europe', (SELECT id FROM countries WHERE name = 'ANDORRA'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_andorra_council.webp'),
       ('175th anniversary of independence of the Grand-Duchy of Luxembourg', (SELECT id FROM countries WHERE name = 'LUXEMBOURG'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Luxembourg.webp'),
       ('Niedersachsen', (SELECT id FROM countries WHERE name = 'GERMANY'), 2014,
        'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Germany_Niedersachsen.webp');
;

