INSERT INTO coins(name, country, year, url)
VALUES ('75th anniversary', 'VATICAN_CITY', 2004, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_va.webp'),
       ('World food program', 'ITALY', 2004, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_it.webp'),
       ('Bartolomeo Borghesi', 'SAN_MARINO', 2004, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_sm.webp'),
       ('EU enlargement', 'FINLAND', 2004, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_fi.webp'),
       ('Henri', 'LUXEMBOURG', 2004, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_lu.webp'),
       ('Olympic Games Athens', 'GREECE', 2004, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2004/comm_2004_el.webp'),
       ('20th World Youth Day', 'VATICAN_CITY', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_va.webp'),
       ('World Year of Physics 2005', 'SAN_MARINO', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_sm.webp'),
       ('1st anniversary of the signing of the European Constitution', 'ITALY', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_it.webp'),
       ('Finlands 50th anniversary of membership of UN', 'FINLAND', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_fi.webp'),
       ('50th anniversary of Austrian State Treaty', 'AUSTRIA', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_at.webp'),
       ('400th anniversary of first edition of Don Quixote', 'SPAIN', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_sp.webp'),
       ('Belgium-Luxembourg Economic Union', 'BELGIUM', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_be.webp'),
       ('50th anniversary of Grand Duke Henri and 100th anniversary of death of Grand Duke Adolphe', 'LUXEMBOURG', 2005, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2005/comm_2005_lu_2.webp'),
       ('500th anniversary of Swiss Pontifical Guard', 'VATICAN_CITY', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_va.webp'),
       ('500th anniversary of Christopher Columbus death', 'SAN_MARINO', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_sm.webp'),
       ('100th anniversary of universal and equal suffrage', 'FINLAND', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_fi.webp'),
       ('Atomium', 'BELGIUM', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_be.webp'),
       ('Schelswig-Holstein', 'GERMANY', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_de.webp'),
       ('Olympic Winter Games', 'ITALY', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_it.webp'),
       ('25th anniversary of Grand-Duke Guillaume', 'LUXEMBOURG', 2006, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2006/comm_2006_lu.webp'),
       ('90th anniversary of Finlands independence', 'FINLAND', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Finland.webp'),
       ('200th anniversary of birth of Giuseppe Garibaldi', 'SAN_MARINO', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_San_marino.webp'),
       ('80th anniversary of Pope Benedict XVI', 'VATICAN_CITY', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_va.webp'),
       ('25th anniversary of death of Princess Grace', 'MONACO', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Monaco.webp'),
       ('Portuguese Presidency of the European Union', 'PORTUGAL', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Portugal.webp'),
       ('50th anniversary of the Treaty of Rome', 'AUSTRIA', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Austria.webp'),
       ('50th anniversary of the Treaty of Rome', 'BELGIUM', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Belgium.webp'),
       ('50th anniversary of the Treaty of Rome', 'FINLAND', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Finland.webp'),
       ('50th anniversary of the Treaty of Rome', 'FRANCE', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_France.webp'),
       ('50th anniversary of the Treaty of Rome', 'GERMANY', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Germany.webp'),
       ('50th anniversary of the Treaty of Rome', 'GREECE', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Greece.webp'),
       ('50th anniversary of the Treaty of Rome', 'IRELAND', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Ireland.webp'),
       ('50th anniversary of the Treaty of Rome', 'ITALY', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Italy.webp'),
       ('50th anniversary of the Treaty of Rome', 'LUXEMBOURG', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Luxembourg.webp'),
       ('50th anniversary of the Treaty of Rome', 'NETHERLANDS', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Netherlands.webp'),
       ('50th anniversary of the Treaty of Rome', 'PORTUGAL', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Portugal.webp'),
       ('50th anniversary of the Treaty of Rome', 'SLOVENIA', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Slovenia.webp'),
       ('50th anniversary of the Treaty of Rome', 'SPAIN', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/joint_comm_2007_Spain.webp'),
       ('Mecklenburg-Vorpommern', 'GERMANY', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_Germany.webp'),
       ('Grand Ducal Palace', 'LUXEMBOURG', 2007, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2007/comm_2007_luxembourg.webp'),
       ('Year of St. Paul', 'VATICAN_CITY', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Vatican.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', 'FINLAND', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Finland.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', 'PORTUGAL', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Finland.webp'),
       ('French Presidency of Council of the European Union', 'FRANCE', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_France1.webp'),
       ('500th anniversary of Primož Trubars birth', 'SLOVENIA', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Slovenia.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', 'BELGIUM', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Belgium.webp'),
       ('European Year of Intercultural Dialogue', 'SAN_MARINO', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_San_Marino.webp'),
       ('60th anniversary of Universal Declaration of Human Rights', 'ITALY', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_Italy.webp'),
       ('Grand-Duke Henri and Château de Berg', 'LUXEMBOURG', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_luxembourg.webp'),
       ('Hamburg', 'GERMANY', 2008, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2008/comm_2008_de.webp'),

       ('Change head of state', 'SPAIN', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Spain_Head.webp'),
       ('Fight against AIDS', 'FRANCE', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_France_2.webp'),
       ('100th anniversary of birth of Ilmari Tapiovaara', 'FINLAND', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Finland_2.webp'),
       ('25th anniversary of the fall of the Berlin Wall', 'VATICAN_CITY', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Vatican.webp'),
       ('600th anniversary of crowning of Barbara Celjska', 'SLOVENIA', 2009, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Slovenia.webp'),
       ('50th anniversary of accension to the throne of Grand-Duke Jean', 'LUXEMBOURG', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Luxembourg_2.webp'),
       ('International Year of Family Farming', 'PORTUGAL', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Portugal_Farming.webp'),
       ('Malta Independence 1964', 'MALTA', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Malta_2.webp'),
       ('90th anniversary of death of Giacomo Puccini', 'SAN_MARINO', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_San_Marino_Puccini.webp'),
       ('150 years of Belgian Red Cross', 'BELGIUM', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Belgium_Cross.webp'),
       ('150th anniversary of union of the Ionian Islands with Greece', 'GREECE', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Greece.webp'),
       ('400 years since the death of Demenikos Theotokopoulos', 'GREECE', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Greece_2.webp'),
       ('Riga - European Capital of Culture 2014', 'LATVIA', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Latvia.webp'),
       ('200 years of Malta Police Force', 'MALTA', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Malta.webp'),
       ('500th anniversary of the death of Bramante Lazzari delle Penne di San Marino', 'SAN_MARINO', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_San_Marino_Lazzari.webp'),
       ('100th anniversary of the birth of Tove Jansson', 'FINLAND', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Finland.webp'),
       ('200th anniversary of the foundation of Arma dei Carabinieri', 'ITALY', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Italy.webp'),
       ('450th anniversary of the birth of Galileo Galilei', 'ITALY', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Italy_2.webp'),
       ('70th anniversary of the Normany landings', 'FRANCE', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_France.webp'),
       ('Official farewell of former Queen Beatrix', 'NETHERLANDS', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Netherlands.webp'),
       ('10th anniversary of Slovak accension to the European Union', 'SLOVAKIA', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Slovakia.webp'),
       ('40th anniversary of the 25th April Revolution', 'PORTUGAL', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Portugal.webp'),
       ('100th anniversary of the start of the First World War', 'BELGIUM', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Belgium.webp'),
       ('UNESCOs World Cultural and Natural Heritage Sites - Park Güell', 'SPAIN', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Spain.webp'),
       ('20 years in the Council of Europe', 'ANDORRA', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_andorra_council.webp'),
       ('175th anniversary of independence of the Grand-Duchy of Luxembourg', 'LUXEMBOURG', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Luxembourg.webp'),
       ('Niedersachsen', 'GERMANY', 2014, 'https://www.ecb.europa.eu/euro/coins/comm/html/comm_2014/comm_2014_Germany_Niedersachsen.webp')








;

