package be.thebelgianeagles.coincollector.domain;

public enum COUNTRY {
    AUSTRIA, BELGIUM, CROATIA, CYPRUS, ESTONIA, FINLAND, FRANCE, GERMANY,
    GREECE, IRELAND, ITALY, LATVIA, LITHUANIA, LUXEMBOURG, MALTA, NETHERLANDS,
    PORTUGAL, SLOVAKIA, SLOVENIA, SPAIN, ANDORRA, MONACO, SAN_MARINO, VATICAN_CITY,
    KOSOVO, MONTENEGRO

    }
