package be.thebelgianeagles.coincollector.domain;

public enum COUNTRY_NAME {
    AUSTRIA, ANDORRA, BELGIUM, CROATIA, CYPRUS, ESTONIA, FINLAND, FRANCE, GERMANY,
    GREECE, IRELAND, ITALY, KOSOVO, LATVIA, LITHUANIA, LUXEMBOURG, MALTA, MONACO,
    MONTENEGRO, NETHERLANDS, PORTUGAL, SAN_MARINO, SLOVAKIA, SLOVENIA, SPAIN, VATICAN_CITY,
}
